services:
    echo:
        build: .
        command: test -w echo --bin /usr/local/bin/rustdis --node-count 1 --time-limit 10
        volumes:
            - ./maelstrom:/maelstrom

    unique-ids:
        build: .
        command: test -w unique-ids --bin /usr/local/bin/rustdis --time-limit 30 --rate 1000 --node-count 3 --availability total
        volumes:
            - ./maelstrom:/maelstrom

    broadcast:
        build: .
        command: test -w broadcast --bin /usr/local/bin/rustdis --node-count 1 --time-limit 20 --rate 10
        volumes:
            - ./maelstrom:/maelstrom

    multi-node-broadcast:
        build: .
        command: test -w broadcast --bin /usr/local/bin/rustdis --node-count 5 --time-limit 20 --rate 10
        volumes:
            - ./maelstrom:/maelstrom

    multi-node-broadcast-network-partitions:
        build: .
        command: test -w broadcast --bin /usr/local/bin/rustdis --node-count 5 --time-limit 20 --rate 10 --nemesis partition
        volumes:
            - ./maelstrom:/maelstrom

    multi-node-broadcast-network-partitions-efficiency:
        build: .
        command: test -w broadcast --bin /usr/local/bin/rustdis --node-count 25 --time-limit 20 --rate 100 --latency 100
        volumes:
            - ./maelstrom:/maelstrom

    serve:
        build: .
        command: serve
        ports:
            - "8080:8080"
        volumes:
            - ./maelstrom:/maelstrom
